name: 'Get and Check Permissions'
description: 'Get and check user permissions for secret access'
inputs:
  github_token:
    description: Github Token for API access
    default: ''
  username:
    description: User to check
    default: ''
  permission:
    description: Required permission level
    default: ''
  error_message:
    description: Error message to display
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
