/*
 * Copyright Contributors to the Malloy project
 * SPDX-License-Identifier: MIT
 */

import {build, BuildOptions, Plugin} from 'esbuild';
import * as esbuild from 'esbuild';
import * as path from 'path';
import fs from 'fs';
import {generateDisclaimer} from './license_disclaimer';
import {getDuckDBExternals} from './utils/fetch-duckdb';

export const defaultBuildDirectory = 'dist/';
let buildDirectory = 'dist/';

export const commonCLIConfig = (development = false): BuildOptions => {
  return {
    minify: !development,
    sourcemap: development,
    bundle: true,
    platform: 'node',
    define: {
      'process.env.NODE_DEBUG': 'false', // TODO this is a hack because some package we include assumed process.env exists :(
    },
    // The @duckdb/node-bindings package dispatches to platform-specific
    // packages (e.g. @duckdb/node-bindings-darwin-arm64/duckdb.node).
    // Those are marked external so they're resolved at runtime.
    // The list is read from @duckdb/node-bindings/package.json so it
    // stays in sync automatically when duckdb updates.
    external: [...getDuckDBExternals(), 'lz4'],
  };
};

const errorHandler = (e: unknown) => {
  console.log(e);
  throw e;
};

const generateLicenseFile = (development: boolean) => {
  const fullLicenseFilePath = path.join(
    buildDirectory,
    'third_party_notices.txt'
  );

  if (fs.existsSync(fullLicenseFilePath)) {
    fs.rmSync(fullLicenseFilePath);
  }
  if (!development) {
    generateDisclaimer(
      path.join(__dirname, '..', 'package.json'),
      path.join(__dirname, '..', 'node_modules'),
      fullLicenseFilePath
    );
  } else {
    fs.writeFileSync(fullLicenseFilePath, 'LICENSES GO HERE\n');
  }
};

function wipeBuildDirectory(buildDirectory: string): void {
  fs.rmSync(buildDirectory, {recursive: true, force: true});
  fs.mkdirSync(buildDirectory, {recursive: true});
}

function copySkills(): void {
  const srcDir = path.join(__dirname, '..', 'skills');
  if (!fs.existsSync(srcDir)) return;
  const destDir = path.join(buildDirectory, 'skills');
  fs.mkdirSync(destDir, {recursive: true});
  for (const file of fs.readdirSync(srcDir)) {
    if (file.endsWith('.md')) {
      fs.copyFileSync(path.join(srcDir, file), path.join(destDir, file));
    }
  }
}

/**
 * The `bin` entry in package.json points at dist/index.js — a thin wrapper
 * that sets MALLOY_CLI_VERSION and requires cli.js. For publish this is
 * generated by scripts/package-npm.ts; for dev builds / `npm link` we need
 * to write it here too, otherwise the globally-linked binary has nothing to
 * execute.
 */
function writeIndexWrapper(): void {
  const pkg = JSON.parse(
    fs.readFileSync(path.join(__dirname, '..', 'package.json'), 'utf8')
  );
  fs.writeFileSync(
    path.join(buildDirectory, 'index.js'),
    `#!/usr/bin/env node\nprocess.MALLOY_CLI_VERSION="${pkg.version}";\nrequire('./cli.js')\n`
  );
  fs.chmodSync(path.join(buildDirectory, 'index.js'), 0o755);
}

export async function doBuild(
  development = false,
  changeBuildDirectory?: string
): Promise<void> {
  if (changeBuildDirectory) buildDirectory = changeBuildDirectory;

  wipeBuildDirectory(buildDirectory);
  generateLicenseFile(development);

  const config = commonCLIConfig(development);
  config.entryPoints = ['./src/index.ts'];
  config.outfile = path.join(buildDirectory, 'cli.js');

  await build(config).catch(errorHandler);
  copySkills();
  writeIndexWrapper();
}

export async function doWatch(development = false): Promise<void> {
  wipeBuildDirectory(buildDirectory);

  const watchRebuildLogPlugin: Plugin = {
    name: 'watchRebuildLogPlugin',
    setup(build) {
      build.onStart(() => {
        console.log('building');
      });
    },
  };

  const config = commonCLIConfig(development);
  config.plugins ??= [];
  config.plugins.push(watchRebuildLogPlugin);
  const ctx = await esbuild.context({
    ...config,
    entryPoints: ['./src/index.ts'],
    outfile: './dist/cli.js',
  });

  console.log('watching...');
  await ctx.watch();
}

const args = process.argv.slice(1);
if (args[1] && args[1].endsWith('watch')) {
  doWatch(true);
} else if (args[0].endsWith('build')) {
  doBuild(true);
}
