name: Test

on:
  pull_request_target:
  push:
    branches:
      - main

jobs:
  test-all:
    runs-on: ubuntu-latest

    steps:
      - name: Check access
        if: ${{ github.event.pull_request.author_association != 'COLLABORATOR' && github.event.pull_request.author_association != 'OWNER' }}
        run: |
          echo "Event not triggered by a collaborator. Association: ${{ github.event.pull_request.author_association }}"
          exit 1
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: GCloud auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.BIGQUERY_KEY }}'
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install
        run: npm ci --loglevel error
      - name: Build and Test
        run: |
          npm run lint
          npm run build
          npm run test-silent
          npm run test-silent-e2e
